// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AuthenticateWithToken(arg1:main.GithubAuthRequest):Promise<main.GithubAuthResponse>;

export function CheckGitInstalled():Promise<main.CheckGitInstalledResponse>;

export function ExportContributions(arg1:main.ExportContributionsRequest):Promise<main.ExportContributionsResponse>;

export function GenerateRepo(arg1:main.GenerateRepoRequest):Promise<main.GenerateRepoResponse>;

export function GetGithubLoginStatus():Promise<main.GithubLoginStatus>;

export function ImportContributions():Promise<main.ImportContributionsResponse>;

export function LogoutGithub():Promise<void>;

export function SetGitPath(arg1:main.SetGitPathRequest):Promise<main.SetGitPathResponse>;
