// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelOAuthLogin() {
  return window['go']['main']['App']['CancelOAuthLogin']();
}

export function CheckGitInstalled() {
  return window['go']['main']['App']['CheckGitInstalled']();
}

export function CreateGitHubRepo(arg1, arg2) {
  return window['go']['main']['App']['CreateGitHubRepo'](arg1, arg2);
}

export function ExportContributions(arg1) {
  return window['go']['main']['App']['ExportContributions'](arg1);
}

export function GenerateRepo(arg1) {
  return window['go']['main']['App']['GenerateRepo'](arg1);
}

export function GetGitPath() {
  return window['go']['main']['App']['GetGitPath']();
}

export function GetUserRepos() {
  return window['go']['main']['App']['GetUserRepos']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportContributions() {
  return window['go']['main']['App']['ImportContributions']();
}

export function LoadUserInfo() {
  return window['go']['main']['App']['LoadUserInfo']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PushToGitHub(arg1) {
  return window['go']['main']['App']['PushToGitHub'](arg1);
}

export function SaveUserInfo(arg1) {
  return window['go']['main']['App']['SaveUserInfo'](arg1);
}

export function SetGitPath(arg1) {
  return window['go']['main']['App']['SetGitPath'](arg1);
}

export function StartOAuthLogin() {
  return window['go']['main']['App']['StartOAuthLogin']();
}

export function VerifyGitHubToken() {
  return window['go']['main']['App']['VerifyGitHubToken']();
}
