// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelOAuthLogin():Promise<void>;

export function CheckGitInstalled():Promise<main.CheckGitInstalledResponse>;

export function CreateGitHubRepo(arg1:string,arg2:boolean):Promise<main.GitHubRepo>;

export function ExportContributions(arg1:main.ExportContributionsRequest):Promise<main.ExportContributionsResponse>;

export function GenerateRepo(arg1:main.GenerateRepoRequest):Promise<main.GenerateRepoResponse>;

export function GetGitPath():Promise<string>;

export function GetUserRepos():Promise<Array<main.GitHubRepo>>;

export function Greet(arg1:string):Promise<string>;

export function ImportContributions():Promise<main.ImportContributionsResponse>;

export function LoadUserInfo():Promise<main.UserInfo>;

export function Logout():Promise<void>;

export function PushToGitHub(arg1:main.PushRepoRequest):Promise<main.PushRepoResponse>;

export function SaveUserInfo(arg1:main.UserInfo):Promise<void>;

export function SetGitPath(arg1:main.SetGitPathRequest):Promise<main.SetGitPathResponse>;

export function StartOAuthLogin():Promise<main.LoginResponse>;

export function VerifyGitHubToken():Promise<void>;
