// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGitInstalled() {
  return window['go']['main']['App']['CheckGitInstalled']();
}

export function ExportContributions(arg1) {
  return window['go']['main']['App']['ExportContributions'](arg1);
}

export function GenerateRepo(arg1) {
  return window['go']['main']['App']['GenerateRepo'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportContributions() {
  return window['go']['main']['App']['ImportContributions']();
}
