// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelOAuth() {
  return window['go']['main']['OAuthService']['CancelOAuth']();
}

export function GetOAuthConfig() {
  return window['go']['main']['OAuthService']['GetOAuthConfig']();
}

export function GetUserEmail(arg1) {
  return window['go']['main']['OAuthService']['GetUserEmail'](arg1);
}

export function HandleOAuthCallback(arg1) {
  return window['go']['main']['OAuthService']['HandleOAuthCallback'](arg1);
}

export function StartOAuth(arg1) {
  return window['go']['main']['OAuthService']['StartOAuth'](arg1);
}

export function StartOAuthWithAutoCallback(arg1) {
  return window['go']['main']['OAuthService']['StartOAuthWithAutoCallback'](arg1);
}
