// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelOAuth():Promise<void>;

export function GetOAuthConfig():Promise<main.GitHubConfig>;

export function GetUserEmail(arg1:string):Promise<string>;

export function HandleOAuthCallback(arg1:main.OAuthCallbackRequest):Promise<main.OAuthCallbackResponse>;

export function StartOAuth(arg1:main.OAuthStartRequest):Promise<main.OAuthStartResponse>;

export function StartOAuthWithAutoCallback(arg1:main.OAuthStartRequest):Promise<main.OAuthCallbackResponse>;
